config/routes.rb
Rails.application.routes.draw do

  resources :sponsors

  get 'user_registrations/new'

  get 'user_registrations/create'

  devise_for :customers
  get 'sign_up_user_index', to: 'sign_up_users#index'
  get 'sign_up_user_customer', to: 'sign_up_users#customer'

  devise_for :users
  get 'checklogin/index'
  get 'checklogin/index', to: 'checklogin#index', as: :checklogin

  get 'logout/index'
  get 'logout/index', to: 'logout#index', as: :logout

  get 'default/index'
  get 'default/login', to: 'default#login', as: :login
  get 'default/cuslogin', to: 'default#cuslogin', as: :cuslogin

  get 'rev/:id', to: 'posts#rev', as: :rev
  get 'customer/new', to: 'customers#new', as: :new

  get 'product/addproduct', to: 'products#addproduct', as: :addproduct

  resources :categories do
    resources :products, except: [:index]
  end

  get :products, to: 'products#index'
  resources :orders
  resources :orderdetails

   root 'default#index'

end

app/models/orderdetail.rb
class Orderdetail < ActiveRecord::Base

  belongs_to :order
  belongs_to :product

  validates :order_id, :product_id, :quantity, :unit_price, presence: true

  scope :by_week, lambda{ where('created_at > ?', Time.now-7.days)  }
  scope :by_day, lambda{ where('created_at > ?', Time.now-1.days)  }

end

app/controllers/orderdetails_controller.rb
class OrderdetailsController < ApplicationController
  before_action :set_orderdetail, only: [:show, :edit, :update, :destroy]

  # GET /orderdetails
  # GET /orderdetails.json
  def index
    @orderdetails = Orderdetail.all
  end

  # GET /orderdetails/1
  # GET /orderdetails/1.json
  def show
  end

  # GET /orderdetails/new
  def new
    @orderdetail = Orderdetail.new
  end

  # GET /orderdetails/1/edit
  def edit
  end

  # POST /orderdetails
  # POST /orderdetails.json
  def create
    @orderdetail = Orderdetail.new(orderdetail_params)

    respond_to do |format|
      if @orderdetail.save
        format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully created.' }
        format.json { render :show, status: :created, location: @orderdetail }
      else
        format.html { render :new }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderdetails/1
  # PATCH/PUT /orderdetails/1.json
  def update
    respond_to do |format|
      if @orderdetail.update(orderdetail_params)
        format.html { redirect_to @orderdetail, notice: 'Orderdetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderdetail }
      else
        format.html { render :edit }
        format.json { render json: @orderdetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderdetails/1
  # DELETE /orderdetails/1.json
  def destroy
    @orderdetail.destroy
    respond_to do |format|
      format.html { redirect_to orderdetails_url, notice: 'Orderdetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderdetail
      @orderdetail = Orderdetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderdetail_params
      params.require(:orderdetail).permit(:order_id, :product_id, :quantity, :unit_price)
    end
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/views/orderdetails/_form.html.slim
= form_for(@orderdetail) do |f|
  - if @orderdetail.errors.any?
    #error_explanation
      h2
        = pluralize(@orderdetail.errors.count, "error")
        | prohibited this orderdetail from being saved:
      ul
        - @orderdetail.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :order_id
    br/
    = f.number_field :order_id
  .field
    = f.label :product_id
    br/
    = f.number_field :product_id
  .field
    = f.label :quantity
    br/
    = f.number_field :quantity
  .field
    = f.label :unit_price
    br/
    = f.number_field :unit_price
  .actions
    = f.submit

app/views/orderdetails/edit.html.slim
h1 Editing orderdetail
= render 'form'
= link_to 'Show', @orderdetail
| \
= link_to 'Back', orderdetails_path

app/views/orderdetails/index.html.slim
h1 Listing orderdetails
table
  thead
    tr
      th Order
      th Product
      th Quantity
      th Unit price
      th colspan: "3" 
  tbody
    - @orderdetails.each do |orderdetail|
      tr
        td= orderdetail.order_id
        td= orderdetail.product_id
        td= orderdetail.quantity
        td= orderdetail.unit_price
        td= link_to 'Show', orderdetail
        td= link_to 'Edit', edit_orderdetail_path(orderdetail)
        td= link_to 'Destroy', orderdetail, method: :delete, data:   confirm: 'Are you sure?'  
br/
= link_to 'New Orderdetail', new_orderdetail_path

app/views/orderdetails/new.html.slim
h1 New orderdetail
= render 'form'
= link_to 'Back', orderdetails_path

app/views/orderdetails/show.html.slim
p#notice= notice
p
  strong Order:
  = @orderdetail.order_id
p
  strong Product:
  = @orderdetail.product_id
p
  strong Quantity:
  = @orderdetail.quantity
p
  strong Unit price:
  = @orderdetail.unit_price
= link_to 'Edit', edit_orderdetail_path(@orderdetail)
| \
= link_to 'Back', orderdetails_path