config/routes.rb
Rails.application.routes.draw do

  resources :sponsors

  get 'user_registrations/new'

  get 'user_registrations/create'

  devise_for :customers
  get 'sign_up_user_index', to: 'sign_up_users#index'
  get 'sign_up_user_customer', to: 'sign_up_users#customer'

  devise_for :users
  get 'checklogin/index'
  get 'checklogin/index', to: 'checklogin#index', as: :checklogin

  get 'logout/index'
  get 'logout/index', to: 'logout#index', as: :logout

  get 'default/index'
  get 'default/login', to: 'default#login', as: :login
  get 'default/cuslogin', to: 'default#cuslogin', as: :cuslogin

  get 'rev/:id', to: 'posts#rev', as: :rev
  get 'customer/new', to: 'customers#new', as: :new

  get 'product/addproduct', to: 'products#addproduct', as: :addproduct

  resources :categories do
    resources :products, except: [:index]
  end

  get :products, to: 'products#index'
  resources :orders
  resources :orderdetails

   root 'default#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

belongs_to :customer
has_many :orderdetails

validates :customer_id, presence: true

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.slim
div style: "margin: 10px 0 0 350px;" 
  = form_for(@order) do |f|
    - if @order.errors.any?
      #error_explanation
        h2
          = pluralize(@order.errors.count, "error")
          | prohibited this order from being saved:
        ul
          - @order.errors.full_messages.each do |message|
            li= message
    .field
      = f.label :customer_id
      br
      = f.number_field :customer_id
    .actions
      = f.submit

app/views/orders/edit.html.slim
#edit
  div style: "margin: 10px 0 0 350px;" 
    h1 Editing order
  = render 'form'
  div style: "margin: 10px 0 0 350px;" 
    = link_to 'Show', @order
    | \
    | \#{link_to 'Back', orders_path}

app/views/orders/index.html.slim
#index
  div style: "margin: 10px 0 0 250px;" 
    h1 Listing orders
    table.table-bordered.table-condensed style: "box-shadow: 5px 5px 1px 1px #888888;" 
      thead
        tr bgcolor: "#191919" 
          th S#
          th Customer
          th colspan: "3"  Action
      tbody
        - i=1
        - @orders.each do |order|
          tr
            td bgcolor: "#191919" = i
            td= order.customer.name
            td= link_to 'Show', order
            td= link_to 'Edit', edit_order_path(order)
            td= link_to 'Destroy', order, method: :delete, data:   confirm: 'Are you sure?'  
          - i=i+1
    br/
    = link_to 'New Order', new_order_path

app/views/orders/new.html.slim
#new
  div style: "margin: 10px 0 0 350px;" 
    h1 New order
  = render 'form'
  div style: "margin: 10px 0 0 350px;" 
    = link_to 'Back', orders_path

app/views/orders/show.html.slim
#show
  div style: "margin: 50px 0 0 350px;" 
    p#notice= notice
    p
      strong Customer:
      = @order.customer_id
    = link_to 'Edit', edit_order_path(@order)
    | \
    | \#{link_to 'Back', orders_path}