config/routes.rb
Rails.application.routes.draw do

  resources :sponsors

  get 'user_registrations/new'

  get 'user_registrations/create'

  devise_for :customers
  get 'sign_up_user_index', to: 'sign_up_users#index'
  get 'sign_up_user_customer', to: 'sign_up_users#customer'

  devise_for :users
  get 'checklogin/index'
  get 'checklogin/index', to: 'checklogin#index', as: :checklogin

  get 'logout/index'
  get 'logout/index', to: 'logout#index', as: :logout

  get 'default/index'
  get 'default/login', to: 'default#login', as: :login
  get 'default/cuslogin', to: 'default#cuslogin', as: :cuslogin

  get 'rev/:id', to: 'posts#rev', as: :rev
  get 'customer/new', to: 'customers#new', as: :new

  get 'product/addproduct', to: 'products#addproduct', as: :addproduct

  resources :categories do
    resources :products, except: [:index]
  end

  get :products, to: 'products#index'
  resources :orders
  resources :orderdetails

   root 'default#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  validates_uniqueness_of :category_name, :case_sensitive => false, message: 'has already taken'
  validates_format_of :category_name, :with => /[a-zA-Z]/, message: 'There should be at least one character.'
  validates :category_name, presence: true

  #category=Category.all
  #category=category.where(id=1)

  def as_json(options= {})
    {label: self.category_name, value: self.products.count}
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.slim
div class="container" style="margin: 10px 0 0 350px; min-height: 340px!important;"
  = form_for @category, validate: true do |f|

    div class="col-xs-4"
      = f.label :category_name
      = f.text_field :category_name,:placeholder => "Electronics" , class:"form-control"


    br
    div class="action" style="margin: 6px;"
      button type="submit" class="btn btn-primary" Submit

  = link_to 'Back', categories_path

app/views/categories/edit.html.slim
= render 'form'

app/views/categories/index.html.slim
#myCarousel-2.myCarousel.carousel.slide
  .carousel-inner
    .active.item
      br
      ul.thumbnails
        - @categories.each do |category|
          li.span3
            .product-box.context-menu-one.box.menu-1
              - if  category.products.last.present?
                = image_tag category.products.last.avatar.url(:medium), 'data-url' => edit_category_path(category), 'data-category-name' => category.category_name
              - else
                = image_tag 'no-image.jpg','data-url' => edit_category_path(category),'data-category-name' => category.category_name
              p.category= category.category_name
              = link_to "View All <span class='cat-name'>#{category.category_name.pluralize}</span>".html_safe, category_path(category), class: 'category'

app/views/categories/new.html.slim
#new
  = render 'form'

app/views/categories/show.html.slim
#all_products
  - if user_signed_in?
    = link_to "Add New Product of <span class='main-nav-black'>#{@category.category_name}</span>".html_safe, new_category_product_path(@category), class: 'link'
  br
  - @category.products.each do |product|
    span.products style= " box-shadow: 5px 5px 25px #666; float: left; margin: 20px; width:220px;  height: 320px; border: solid 1px #fff; border-radius: 25px; overflow: hidden"
      span.product-image
        = image_tag product.avatar.url(:medium)
      p.product-name style= "margin-left: 10px"
        = product.product_name
        br
        | Rs. #{product.unit_price}
        br
        = link_to 'View Full Detail of  Product', category_product_path(@category, product)
  div style = "clear: both"