config/routes.rb
Rails.application.routes.draw do

  resources :sponsors

  get 'user_registrations/new'

  get 'user_registrations/create'

  devise_for :customers
  get 'sign_up_user_index', to: 'sign_up_users#index'
  get 'sign_up_user_customer', to: 'sign_up_users#customer'

  devise_for :users
  get 'checklogin/index'
  get 'checklogin/index', to: 'checklogin#index', as: :checklogin

  get 'logout/index'
  get 'logout/index', to: 'logout#index', as: :logout

  get 'default/index'
  get 'default/login', to: 'default#login', as: :login
  get 'default/cuslogin', to: 'default#cuslogin', as: :cuslogin

  get 'rev/:id', to: 'posts#rev', as: :rev
  get 'customer/new', to: 'customers#new', as: :new

  get 'product/addproduct', to: 'products#addproduct', as: :addproduct

  resources :categories do
    resources :products, except: [:index]
  end

  get :products, to: 'products#index'
  resources :orders
  resources :orderdetails

   root 'default#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      can :manage, :all
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  validates_uniqueness_of :category_name, :case_sensitive => false, message: 'has already taken'
  validates_format_of :category_name, :with => /[a-zA-Z]/, message: 'There should be at least one character.'
  validates :category_name, presence: true

  #category=Category.all
  #category=category.where(id=1)

  def as_json(options= {})
    {label: self.category_name, value: self.products.count}
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable

  validates_presence_of :email
end

app/models/order.rb
class Order < ActiveRecord::Base

belongs_to :customer
has_many :orderdetails

validates :customer_id, presence: true

end

app/models/orderdetail.rb
class Orderdetail < ActiveRecord::Base

  belongs_to :order
  belongs_to :product

  validates :order_id, :product_id, :quantity, :unit_price, presence: true

  scope :by_week, lambda{ where('created_at > ?', Time.now-7.days)  }
  scope :by_day, lambda{ where('created_at > ?', Time.now-1.days)  }

end

app/models/product.rb
class Product < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  belongs_to :category
  has_many :orderdetails
  validates :product_name, :unit_price, :quantity, :desc, :category_id, presence: true
  validates :unit_price, :quantity, :category_id, numericality: { only_integer: true }
  validates_length_of :isbn, :minimum => 12
  validates_uniqueness_of :isbn

  validates :product_name, exclusion: {in: %w(www http .com), message:  "These are reserved words"}

  scope :by_cat, lambda{ |cat| where(category_id:  cat) }
  scope :by_price, lambda{ |price| where('unit_price > ?',   price) }
  scope :by_week, lambda{ where('created_at > ?', Time.now-7.days)  }


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :avatar, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :avatar
  validates_with AttachmentSizeValidator, :attributes => :avatar, :less_than => 1.megabytes

  def self.total
    i=1
    total=0
    all.each do |product|
      i=i+1
      total=total + product.quantity * product.unit_price
    end
    total
  end

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_attached_file :avatar, styles: { xtralarge: "940x323>" ,medium: "250x110>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController

  def index
    session.clear
    redirect_to default_index_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checklogin_helper.rb
module CheckloginHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/orderdetails_helper.rb
module OrderdetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sign_up_users_helper.rb
module SignUpUsersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield() %>



</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
      body{
          margin: 0px;
          padding: 0px;
      }
  </style>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body style="background-color: #F8F8F8;">

<div id="top-bar" class="container">
  <div class="row">
    <div class="span4" style="float: right;">
      <span style="font-weight: bold;"><%= link_to "Signed in as... #{current_user.email}" if user_signed_in?%></span>
    </div>
    <div class="span8">
      <div class="account pull-right">
        <ul class="user-menu">
          <br>

          <% if user_signed_in? %>
              <li><%= link_to 'Add Category', new_category_path %></li>
              <li><%= link_to 'All Products Report', products_path %></a></li>
              <li><%= link_to 'Customers', sign_up_user_customer_path %></li>
              <li><%= link_to 'Users', sign_up_user_index_path %></li>
              <li><%= link_to 'New User', new_user_registration_path  %></li>
              <li><%= link_to 'Sopnsors', sponsors_path  %></li>

              <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
          <% end %>

          <% if customer_signed_in? %>
              <li><%= link_to 'Logout', destroy_customer_session_path, :method=>'delete' %></li>
          <% else %>
              <% if user_signed_in? %>
              <% else %>
                  <li><%= link_to 'Customer Login', new_customer_session_path %></li>
                  <li><%= link_to 'Staff Login', new_user_session_path %></li>
              <% end %>
          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>
<div id="wrapper" class="container">
  <section class="navbar main-menu">
    <div class="navbar-inner main-menu">
      <%= link_to 'RIMS', default_index_path, class:'app-name' %>
      <nav id="menu" class="pull-right">
        <ul>
          <li><%= link_to 'All Categories', categories_path %>
          </li>

          <% count = 0 %>
          <% other_catagories = []%>
          <% Category.all.each do |category| %>
              <% if count <= 6%>
                  <li class="context-menu-one box menu-1"><%= link_to category.category_name, category ,data: {url: edit_category_path(category), category_name: category.category_name}%></li>
              <% else %>
                  <% other_catagories << category %>
              <% end %>
              <% count = count + 1 %>
          <% end %>

          <li>
            <a href="#"> Other Categories &#9662;</a>
               <ul>
                  <% other_catagories.each do |category| %>
                     <li class="context-menu-one box menu-1 other_category"><%= link_to category.category_name, category ,data: {url: edit_category_path(category), category_name: category.category_name}%></li>
                  <% end %>
               </ul>
          </li>

        </ul>
      </nav>
    </div>
  </section>

  <div class="main-con">
    <%= yield %>
  </div>

  <section id="copyright">
    <span>© 2015 - All Rights Reserved - <%= mail_to "sajjad.murtaza49@yahoo.com", nil, :style => 'font-weight: bold' %></span>
  </section>
</div>



</body>
</html>